### ISSUE TITLE
api fox 是否能授权克隆，用于学习研究呢？

### ISSUE THREAD

**Issue by cvpv** [chansee97/nove-admin-nest#1]
大佬的前端项目nova-admin，依赖于该项目的接口设计，我想改点返回值的数据，但是看到不允许克隆该文档

![image](https://github.com/chansee97/nove-admin-nest/assets/84720311/f2ce6c7f-1898-46e2-b1e7-07d628306a32)

**Comment by chansee97** [comment]
并不依赖该项目的接口设计，目前实际的接口使用和该项目接口并没有完全对接，而且用到的接口并不多https://apifox.com/apidoc/shared-2b1abeb5-6e78-425e-a4ff-d7277ae83bf0/api-151070438

**Comment by cvpv** [comment]
> 并不依赖该项目的接口设计，目前实际的接口使用和该项目接口并没有完全对接，而且用到的接口并不多https://apifox.com/apidoc/shared-2b1abeb5-6e78-425e-a4ff-d7277ae83bf0/api-151070438

好的，谢谢大佬。
